FROM mysql/mysql-server

# Database
ENV MYSQL_DATABASE jbpmDB
ENV MYSQL_USER jbpmDB
ENV MYSQL_PASSWORD kwesta89634893wale3467893@f567hj

# Copy the Initialization scripts
COPY ./scripts/ /docker-entrypoint-initdb.d/

MAINTAINER Edward Banfa (ebanfa@gmail.com)
